### ISSUE TITLE
Visual Studio 2019 Community support

### ISSUE THREAD

**Issue by jerone** [jonkeda/VarTypeViewer#2]
It [appears](https://github.com/jonkeda/VarTypeViewer/blob/a50cfebeaeff27c9e432abd4f81d06c406f85f43/VarTypeViewer/source.extension.vsixmanifest#L9-L11) that there is no VS2019 Community support, only in VS2017. But Pro & Enterprise are supported in VS2019.

Can Community be enabled for VS2019?!

**Comment by michaelm7456** [comment]
I've raised a Pull Request [here](https://github.com/jonkeda/VarTypeViewer/pull/3) with a change to allow the Extension to work with Visual Studio 2019.

This should also resolve [Issue# 1 - VS2019 (Preview) support](https://github.com/jonkeda/VarTypeViewer/issues/1)

Hope this helps!

**Comment by michaelm7456** [comment]
Hi @jerone, that's the Pull Request to allow this Extension to work with '**Visual Studio Community 2019**' now merged in.

[Pull Request #3 ](https://github.com/jonkeda/VarTypeViewer/pull/3)

I think once the latest changes to this Repo are published to the Visual Studio Gallery the latest changes should be available for everyone, and this issue can be closed.

If you need a copy of the Extension with VS 2019 Community Support to get by in the meantime I've attached a link below. (You'll have to extract it first after downloading as Github doesn't let me upload the VSIX file directly to comments.)

[VarTypeViewer.zip](https://github.com/jonkeda/VarTypeViewer/files/5075237/VarTypeViewer.zip)
